version: "3.8"

services:
  client:
    build:
      context: .
      target: builder
    command: npm run dev:client
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:5000

  server:
    build:
      context: .
      target: builder
    command: npm run dev:server
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/recipe_manager
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=recipe_manager
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
