services:
  - name: recipe-manager-backend
    type: web
    runtime: node
    rootDir: apps/backend
    buildCommand: npm install --include=dev --force && npm run build
    startCommand: npm run start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: recipe-manager-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: JWT_REFRESH_EXPIRES_IN
        value: 30d
      - key: FRONTEND_URL
        value: https://recipe-manager-spa-frontend.vercel.app
      - key: ALLOWED_ORIGINS
        value: https://recipe-manager-spa-frontend.vercel.app

  - name: recipe-manager-frontend
    type: web
    runtime: node
    rootDir: apps/frontend
    buildCommand: npm install --include=dev --force && npm run build
    startCommand: npm run preview -- --port 4173
    envVars:
      - key: NODE_ENV
        value: production

databases:
  - name: recipe-manager-db
    plan: free 