services:
  - name: recipe-manager-backend
    type: web
    runtime: node
    region: oregon
    plan: free
    branch: main
    rootDir: apps/backend
    buildCommand: "npm install --include=dev && npm run build --workspace=apps/backend"
    startCommand: "npm run start --workspace=apps/backend"
    healthCheckPath: /api/health
    preDeployCommand: "npx prisma migrate deploy && npx prisma generate"
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: recipe-manager-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: FRONTEND_URL
        fromService:
          type: web
          name: recipe-manager-frontend
          property: url

  - name: recipe-manager-frontend
    type: web
    runtime: static
    region: oregon
    plan: free
    branch: main
    rootDir: apps/frontend
    buildCommand: "npm install && npm run build --workspace=apps/frontend"
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: recipe-manager-backend
          property: url

databases:
  - name: recipe-manager-db
    plan: free
    region: oregon
    postgresMajorVersion: "14" 