services:
  - name: recipe-manager-backend
    type: web
    runtime: node
    region: oregon
    plan: free
    branch: main
    rootDir: ./
    buildCommand: "npm install --include=dev --force && npm run build --workspaces"
    startCommand: "npm run start --workspace=apps/backend"
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: recipe-manager-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: JWT_REFRESH_EXPIRES_IN
        value: 30d
      - key: FRONTEND_URL
        value: https://recipe-manager-spa-frontend.vercel.app
      - key: ALLOWED_ORIGINS
        value: https://recipe-manager-spa-frontend.vercel.app

databases:
  - name: recipe-manager-db
    plan: free
    region: oregon 