services:
  - name: recipe-manager-backend
    type: web
    runtime: node
    region: oregon
    plan: free
    branch: main
    rootDir: ./
    buildCommand: "npm install && npm run build --workspace=apps/backend"
    startCommand: "npm run db:deploy --workspace=apps/backend && npm run start --workspace=apps/backend"
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: recipe-manager-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: FRONTEND_URL
        value: https://recipe-manager-frontend.onrender.com
  - name: recipe-manager-frontend
    type: web
    runtime: static
    branch: main
    rootDir: ./
    buildCommand: "npm install && npm run build --workspace=apps/frontend"
    staticPublishPath: apps/frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_BASE_URL
        value: https://recipe-manager-backend.onrender.com

databases:
  - name: recipe-manager-db
    plan: free
    region: oregon 